armada-ths/ais

events/admin.py, exhibitors/admin.py
**UPDATE**: Changes are now implemented for Events as well.
This PR eliminates the risk that someone uploads any other images other than logo_original and ad_original. The other images fields are generated from the two aformentioned ones and should therefore not be modified. The generated images are now read-only but are still available in the admin in case someone wants to see a preview.
The admin site for catalogue info has also been refactored using collapsable classes, improving readability.
Images:
----------------------------
----------------------------
----------------------------
----------------------------
=> Refactor the catalogue info admin and make images read-only

ais/common/settings.py, ais_nginx.conf, ais_uwsgi.ini, api/views.py
- ETag middleware in django (for all requests, any reason why not?)
- Prefetch related models in api/exhibitors
- Cache api requests in nginx, this will require an nginx reload after deploy
=> Etag nginx

events/admin.py, exhibitors/admin.py, lib/util.py
Generated images can now be previewed in the admin.
It's a nice way to see what's going to be displayed in the apps and on the web site.
=> Add image previews for events and catalogue info

companies/urls.py, templates/companies/contact_form.html
The bug was that when in sales view for a sale (/fairs/2017/sales/2), the button for "New contact" gave server error. The url the button tried did not exist. The correct url was commented away. I uncommented correct row and added styling with crispy forms tag.
Tested the button as admin, also as "kam" user, a user with the same permissions as key account manager in ais.
=> Fixed bug when creating new company contact

register/views.py
Stand height and area products should now be created in the database when form is submitted.
The database, email and js in confirm and submit works, however initialization of fields upon new login does not work. So when the exhibitor logs in and out again the choicebars and js will show the default value and not the chosen one even though it is in the db.
=> bugfix regarding additional stand height and area.

register/forms.py
product as select field now works for db, email, js on confirm and submit and preloads form fields, that is the bug where exhibitors requesting extra stand area and height should work completely.
Things to test:
1. If products are selected and saved the summary on confirm & submit should be updated
2. The product on the db should be updated/created
3. The email should contain the correct info
4. On logging out and in the correct products should be preloded into the selection fields
=> Bugfix for products extra stand area and height

register/views.py
See commit on Aug 09, 2017 for info,
things to do before test:
1. create a fair that is not current (i.e create a Arnada Fair 2016 and make sure the "current box" is not checked" (also make sure you have a current fair, e.g "Armada Fair 2017" or whatever you have your current fair set to, with both fairs having signup contracts else you'll get an error)
2. add an exhibitor for some test company to the fair you just created (Armada Fair 2016)
3. add som product (i.e, a stand height with some wierd spec that you connect to the fair you just created)
4. Add this product to the exhibitor you just created
Thigs to test:
log in to the cr with this exhibitor, then make sure that:
1. The order you just created is NOT seen in the form fields (only current products should be seen)
2. Upon save, …
=> Bugfix exhibitor transition year

register/views.py
Fixes issue where
1. Exhibitors from previous year gets overwritten
2. Exhibitor from previous year get products from precious year inlined with the new ones
(i.e with this fix it should be so that, a new exhibitor for this years fair is created, still keeping the old exhibitor at precious years fair in the db, where the correct products are loaded into the cr)
Things to do before test ON ais2 (not on ais hehe):
1. Create a test user (preferrably with your real email so you can verify the confirm mail later)
2. Connect test user to a company from last years fair that is already an exhibitor (a company that is an exhibitor at Armada 2016)
3. If doesNotExist any products, add some in the exhibitors view at ais2.armada.nu/fairs/2016 (for example extra stand area for fair 2016)
Things to …
=> bugfix for exhibitors from previous years

scripts/orders-bugfix.py
Adds a script that will fix faulty orders in the db (due to an earlier bug).
Problem: In the db there are some orders from last year where the exhibitor is from this year and the product is from last year.
Reason: When a company submitted pr, the exhibitor from last year was overwritten and last year orders were connected to this year exhibitor. This bug is now solved.
Test:
In admin-view: Create an exhibitor for this year. Create a product for last year and one for this year.  Create following orders:
Two that is connected to this year exhibitor and last year product.
One that is connected to this year exhibitor and this years product.
One that is connected to last year product and last year exhibitor.
Run script.
Check that only one new exhibitor is created and that both faulty orders …
=> Script to fix db

events/admin.py, exhibitors/admin.py, orders/admin.py, register/admin.py
Updated exhibitor csv function to include some more fields and added filter and sort options to multiple admin views.
Test:
- go to http://localhost:8000/admin/exhibitors/exhibitor/ and try some of the filter to the right (escpecially the fair)
- check the checkboxes for a couple of exhibitors (preferrable some you know have done some choices in their exhibitor application) and chose the action 'export as csv'. Open the downloaded csv file and compare result with those exhibitors application
- go to admin/events/event/ and try the filters. Make sure the ordering is fair first, then event name
- go to admin/orders/order/ and try the filters. Make sure the ordering is fair first, then exhibitor name. You should be able to search both for product and exhibitor name
- go to …
=> Csv exhibitor + admin views

ais_static/js/banquet_attendant.js, banquet/forms.py, banquet/urls.py, banquet/views.py, root/urls.py, static/js/banquet_attendant.js, templates/banquet/banquet_attendant.html, templates/banquet/banquet_attendants.html, templates/banquet/external_signup.html, templates/banquet/thank_you.html
New BanquetAttendant model in banquet app. Not much to test or check. All connections to the old model has been changed. (((((((( This is already in AIS2! ))))))
What is new and what can you check:
1. You can view all banquet attendants from current year ONLY in fairs/{year}/banquet. 
2. Click on an attendant's name to view/edit the attendant in the url fairs/{year}/banquet/attendant/{pk}.
3. In the url fairs/{year}/banquet/attendant/new one can create a new attendant.
4. In fairs/{year}/banquet/signup you can as a external person signup for the banquet. Your info will be saved when revisiting the signup. I will add compatability for those without kth and armada account further down the road. Right now this is what we need.
=> Banquet app

api/serializers.py
Bug fix
Signup link in events should be https://ais.armada.nu/fairs/2017/events/pk/signup instead of https://ais.armada.nu/events/pk/signup.
=> Changed link to include fair

api/serializers.py, api/tests.py
Made sure the programme-field in the api/organization returned the name and not the whole object. 
Test:
see #410. Also add a programme to one of the profiles and make sure it is returned correctly.
=> Fixed programme-field

recruitment/forms.py, recruitment/models.py, recruitment/views.py, templates/recruitment/recruitment_application_table.html
Removed registration year and role column in favor of two new ones: role & priority. 
The new role column contains every role that can be applied for in the given recruitment period.
The new priority column contains '1:st', '2:nd', '3:rd', ... corresponding to the priority the applicant has given for each role. It is decided by the eligible_roles attribute in the recruitment period, but capped at 3 (and will be set to 1 if eligible_roles < 1). 
If both role and priority are selected, the application table will only display the applications of people who have applied for the given role with that priority, but still display all the roles that person has applied for. For instance, searching for 'Head of IT' with priority '2:nd' in the project group recruitment looks like this:
In the (weird) …
=> 001 search desired roles

companies/views.py, templates/companies/statistics.html
The statistics page of the CRM system was showing previous year's responsibles. Responsibiliites are not year specific but the group that is connected to the responsibility is - therefore only responsibles connected to a group for the current fair are now added to the list of responsibilitites.
Also fixed so that contracts that do not have any signatures don't show an empty graph but are hidden.
=> 017 crm statistics

exhibitors/admin.py, exhibitors/models.py, register/forms.py
- Updated catalogue forms to only include alternatives that have the include_in_form set to True.
- Updated admin view to manage catalogue alternatives easier with regards to the new attribute.
- Sort catalogue alternatives in ascending order based on name always (defined in models.py).
=> 057 update catalogue forms

register/forms.py, register/views.py, templates/register/inside/registration_complete.html
Currently looks like this if the user tries to save the logistics form without checking the box.
Some implementation details:
- If the box is ticked when the form is saved, it will be ticked in the page that loads immeadiately after. However, if the user exits the session, the box needs to be ticked again. It is not associated with the model at all.
- The collapsible fields seem to default to close, so it's not immeadiately apparent for the user that something has gone wrong when saving.
=> 041 logistics details checkbox

companies/urls.py, companies/views.py, templates/companies/companies_list.html, templates/companies/contracts_export.html, templates/companies/email.html, templates/companies/groups.html, templates/companies/statistics.html
The CRM app now has the same functionality as the recruitment app where a user can view and copy all names and email addresses to groups of contacts.
=> added email address tab to CRM

templates/register/inside/base.html
The company contact can now log out of the registration page if needed. The user will return to the /register page if so.
=> added signout of registration page

events/views.py
Currently, the event page in AIS shows events from 2018 in the list. Clicking on an event from 2018 while being at /ais.armada.nu/fairs/2019/events/ gives 'Server Error 500'. This fix will filter out the events for the current year only. Then Ella can start adding events for 2019 and not mix them up with events from 2018.
=> Filter event list by fair year

companies/models.py, companies/views.py, templates/companies/companies_list.html
Allows contact names, numbers and emails to be searched by the same search field as used to search the rest of the table. This is achieved by adding extra (hidden) columns to the table.
It certainly doesn't make the CRM faster, but I don't find the slow-down especially noticeable considering it's already pretty dismal...
=> 005 crm search parameters

banquet/views.py, payments/urls.py, payments/views.py, templates/banquet/invitation_external.html, templates/payments/checkout.html
Some edits had to be made to the previous pull request of the Stripe payment update. With the new updates we avoid creating more than one payment intent per invited person.
The payment method now works for external users that are invited to the banquet. Note that internal invitations, after party tickets and event payments still has to be updated.
=> 126 Stripe payment bugs fixed

api/deserializers.py, api/serializers.py, api/urls.py, api/views.py, exhibitors/api.py, exhibitors/serializers.py
Update the matching API and use the updated matching algorithm. Also added API for getting the choices to the front end so that they don't have to be hard-coded.
N.B. This is dependent on the [related pull request in the matching repo](https://github.com/armada-ths/matching/pull/2).
The new algorithm is documented [here](https://drive.google.com/open?id=1oFa7uJOVBTqALeaXi_P2GkPNsfHojGa2wMzN_I3hk6o). The updated API documentation resides [here](https://drive.google.com/open?id=1Ks8_eDOseTeqZCsk1hSYN0tRHo84m3ysAPgEi2BwW20).
I updated exhibitor serialization wherever I came across it... So in exhibitors/api.py, exhibitors/serializers.py and api/serializers.py.
=> 090 update matching for 2019

banquet/forms.py, banquet/models.py, banquet/views.py, templates/banquet/invitation_external.html, templates/banquet/invitation_internal.html, templates/banquet/manage_invitation.html, templates/banquet/manage_invitations.html, templates/banquet/manage_participant.html, templates/banquet/manage_participants.html
With the new payment solution for banquet tickets a user can become a participant and not have paid - some middle land in between Going and Not going. For this I have added a new invitation status "Has not paid" which is set if there is a participant buth this participant has not paid yet.
Normally a user should press the "Not going" button if he or she does not want to attend the banquet, and this will remove the participant, And hopefully everyone who press the "Proceed to payment" button intends to finish their signup. So the "Has not paid" should rarely be the case, but if so we can now see it both in the invitations view and in the participants view.
=> Banquet invitation status update

exhibitors/api.py
Updates to comply with task 091.
Every attribute has the same name as it does in the model.
- String representation of location (which includes parent location)
- Vyer map link (string)
- Location special (name only - string)
- Climate compensation boolean
- Link to exhibitor flyer (string)
Exhibitor competences (list of string) and exhibitor cities (string) has been added previously (as part of updating the matching API).
Please test when database has more content, so that for instance the map and flyer links work (currently only sends null).
Also solves task 160.
=> 091 update exhibitors api

events/api.py
The signup for events was previously showing all teams when the user had created, joined or left a team. Should only show the ones that allow student join.
=> fix: student signup only showing student/mix teams

templates/events/emails.html, templates/events/event_edit.html
Adds an E-mails tab to the event page. The emails are presented in a textbox, similarly to the recruitment e-mails page. I'll post a screenshot in Asana since this is public and I don't wanna put anybody's e-mail address out there. :)
=> 118 event email list

register/views.py, templates/register/inside/banquet.html, templates/register/inside/lunchtickets.html
Added functionality to set a deadline for when lunch tickets and banquet tickets can be created/edited on the registration page for companies. Right now this is hardcoded in the register views.py but the times should preferrably be added as fields to the fair object. This will be implemented at a later time since it had som chain issues to fix connected to adding fields to the fair model.
=> Deadlines for tickets creation/edit for companies

exhibitors/models.py, exhibitors/views.py, templates/exhibitors/exhibitors.html
In addition to for example check in time one can now also select to view the check in comments already in the list of exhibitors - previously the comment was only shown in the view of a single exhibitor.
=> Added ability to show check-in comments in exhibitor overview list

exhibitors/api.py
This allows you to call `/api/exhibitors` either in the way you've always done it, to get the exhibitors for the current year, or with an additional `year` query string parameter, to get the exhibitors from another year, e.g. `/api/exhibitors?year=2019`. Could be useful to somebody... Perhaps...!
=> Let the frontend choose to get an exhibitor list from another year

companies/views.py
The for loop that goes through all fairs before sending them to the template rendering function had a variable with the name `fair`, which caused the function parameter `fair` to be overwritten. This could lead to an unexpected fair showing up in the template, depending on which fair the for loop handled in its last iteration.
=> Don't overwrite the fair variable with a new reference

exhibitors/models.py
Changed the placement_wish field to say "No preference" instead of "----" when the value is None. Simple change of choices attribute in exhibitors/models.py.
**Full testing steps from untouched ais:**
- Login on admin
- /admin/register/signupcontract/add/ create initial+complete for Armada 2020
- /admin/fair/fair/5/change/ set initial end date after today, complete start date far into future, complete end date even farther into future
- Logout from admin
- Login on salescontact1 at /register
- Sign the contract
- Logout from salescontact1
- Login on admin
- /admin/exhibitors/exhibitor/add/ add Sales Company 1 as an exhibitor to Armada 2020
- /admin/fair/fair/5/change/ set initial end date a few days back, set complete start day to yesterday
- Logout from admin
- Login on salescontact1 at …
=> 078 - IR /CR - Placement_wish '----' choice

templates/banquet/manage_participant.html
The QR-codes were working all along, but required a background image to be uploaded for the corresponding Banquet object. Additionally, a participant's link would not work if they had not been assigned a seat. To prevent these links from being opened in the future (prompting a 500 Server Error), the link is hidden until these two conditions are true and instead a text is shown explaining why the link is not.
**Full testing steps from untouched ais:**
0. ./dev-runserver.sh (sudo may or may not be needed)
1. Login to the ais as admin (on localhost, duh)
2. In the admin view, under Banquet -> Banquets, create a new Banquet belonging to the Armada 2020 fair. Add a name, a date, and a time.
3. In the admin view, under Banquet -> Participants, create a new participant. Select the banquet you …
=> Banquet: Fix a working QR-code for non-AIS people's tickets

lib/CAS_callback.py, lib/KTH_Catalog.py
**Problem**
Some users appear with empty email, first name and last name although they signed in using their KTH account.
**Expected results**
User information should be retrieved from KTH if they sign in with their KTH account and the kth_synchronize field equals to True. Also, existing empty info should be filled up once the user signs in.
**Background**
Each time a user sign in with their KTH account, an attempt to get the updated user information from KTH is made using LDAP. For some reason, it seems that LDAP not always work and, therefore, the user information (i.e email, first name and last name) remains empty.
**Proposal**
This PR adds a second attempt to get the user information using the public [KTH Profile API](https://api.kth.se/api/profile/swagger/?url=/api/profile/swagger.jso …
=> Get user info from KTH Profiles API

templates/base.html
Removed the hyperlink to Slack channel the bottom of the AIS page.
=> removed hyperlink from base.html

dev-runserver.sh, requirements.txt, shared_js/config/webpack.config.js
#701 
- The changes made are currently working locally on my linux machine but haven't been able to test it out in vagrant or others devices.
- The changes made are only downgrading the dependencies. 
- I suspect that we will need to do some changes in how we build the webpack as of now we only watch it but never build it(I think, haven't look it through when it comes to vagrant)
- I also suspect that vagrant are using an old version of node and npm which can be the cause of newer problem. **I will need to know which version of `nodejs` and `npm` we have on the AIS server** @rrudling .
=> 701: Refactor: Event tab, (remove react ?)

banquet/views.py
There were hard-coded changes that closed the after-party-invitations. I shall work now.
You shall be able to see a invite screen.
=> #719: Fix: Invite friends to the after party

register/views.py
Fetch the fair from the current timezone year instead of the current set fair. This is because the registration period of the current fair is not opened yet, and we still want to be able to see the orders of every company before the new year shift.
=> fix(register): Fetch the fair from the current timezone year

api/urls.py, api/util.py, api/views.py
Fixes: #814 by adding an endpoint `/api/recruitment_data?fair_year={FAIR_YEAR}` (with `fair_year` parameter being optional, defaulting to current fair), giving anonymized statistics about recruitment applications. The endpoint requires the `recruitment.view_recruitment_applications` permission. Exposed fields are: `status, gender, programme, preferred_language`.
- Does not add any new database migrations, so should be risk-free to push to production. See #816.
- Hides the information behind a permission role, so should not leak any information to unauthorized users. If it were to to that, the information is anonymized.
=> feat: Add recruitment_data api endpoint

.github/PULL_REQUEST_TEMPLATE.md
Fixes: #826 by removing the redundant PR checkbox checkbox.
=> doc: Remove format PR checkbox

fair/views.py
Fixes: #821 by removing an unnecessary variable assembling all possible roles in the AIS (there are a lot of roles, so this takes time). This variable does not seem to be used anywhere in the code, but I'm not entirely sure of this, so the fix is a bit risky. Have tested it locally with a copy of the production database, and nothing seems to break.
The relevant file which consumes these variables is here (note that roles are not mentioned anywhere): https://github.com/armada-ths/ais/blob/master/templates/fair/home.html
=> fix: Remove slow roles variable from call to render home page

api/serializers.py, api/urls.py, api/views.py
Fixes: #862 by creating a new API `api/organization/v2` which displays OTs and PGs in their group, with their delegated roles. A new API endpoint had to be created because the structure of the JSON is changed. We will try to deprecate the v1 organization API #864 eventually.
Fixes #863 by removing absolute URLs from the profile images, and instead using relative URLs.
---
- https://app.asana.com/0/0/1204488023105642
=> feat: Add organization v2 API

ais/production/settings.py
Fixes: #866 (maybe) by removing allowed hosts which doesn't seem to work anymore with AWS.
According to https://stackoverflow.com/questions/40582423/invalid-http-host-header you usually don't use allowed hosts when hosting in docker.
=> fix: Remove allowed hosts

ais/common/settings.py, ais/production/settings.py, requirements.txt
(Maybe) Fixes #866 by adding a EB health check plugin, and reintroducing the allowed hosts for production settings (which are required). Currently the production page crashes because the EB health check in AWS is not part of the allowed hosts, and never will be because the IP is different every time. This plugin somehow works around that.
=> fix: Add EB health check plugin

recruitment/views.py
=> fix: Fix permissions for creating new recruitment period

apps/complete_registration/src/screens/form/sidebar/PageCard.tsx, apps/complete_registration/src/store/form/form_selectors.ts
The progression selectors used for pages wasn't connected to custom getProgression function before
Fixes: #
=> fix: Fix page progression bug that ignored custom getProgression function

register/urls.py, register/views.py
Fixes: #939
This change allows a company to visit the old FR page, by going to the previous URL `<company_id>/registration`. A sales person will need to give the URL to the company if they for some reason would need to access the old page.
=> chore: Move new FR page to live

exhibitors/api_urls.py
=> Remove cors API exhibitors

accounting/admin.py
`/admin/accounting/order/` was crashing on add, change. This was because of `ExportBatch` not being defined in admin, and could thus not be rendered.
=> fix: Add export batch as admin model

dashboard/api/registration/ir.py, dashboard/api/registration/registration.py, dashboard/api/registration/types/util.py
The accepted and rejected states were not defined, causing the site to crash when in `AFTER_IR`. 
fix: The exhibitor field wasn't propagated through handle_ir
=> fix: Accepted/rejected status and propagate exhibitor

apps/dashboard/src/forms/fr_accounting/components/DiscountCard.tsx, apps/dashboard/src/forms/fr_accounting/components/ProductOrderingCard.tsx, apps/dashboard/src/forms/fr_accounting/product.page.tsx, apps/dashboard/src/shared/hooks/api/useDashboard.tsx, dashboard/api/registration/response.py
=> fix: Add backend compatibility with specific products

apps/dashboard/src/forms/fr_accounting/summary.page.tsx, apps/dashboard/src/screens/dashboard/timeline_steps.tsx, templates/register/email/cr_complete.html
=> fix: Spelling

apps/dashboard/src/forms/fr_accounting/components/ProductOrderingCard.tsx, apps/dashboard/src/forms/fr_accounting/useAccounting.tsx, apps/dashboard/src/forms/ir_signup/ir_registration.page.tsx
=> fix: Add debounce to cart

apps/dashboard/src/forms/transport/transport_info.page.tsx
=> fix: Change logistics information

Dockerfile, ais/common/settings.py, requirements.txt
During high load hours, we are getting the error `django.db.utils.OperationalError: FATAL: remaining connection slots are reserved for non-replication superuser connections`. This causes the whole site to freeze for all users for a while (except /admin).
The reason is Django not reusing connections to the database.
Possible solution: https://pypi.org/project/django-db-connection-pool/
=> fix: Add DB connection pool library

ais/common/settings.py
This should hopefully add persistent connections https://devcenter.heroku.com/articles/python-concurrency-and-database-connections
=> fix: Add CONN_MAX_AGE to database settings

banquet/functions.py, banquet/views.py, templates/banquet/manage_invitations.html
=> fix: Add email sent column

apps/dashboard/src/screens/dashboard/screen.tsx, dashboard/api/registration/response.py, fair/models.py
=> fix: Show catalogue after CR
