armada-ths/ais

- docs/getting_started_docker.md
Although Vagrant and Virtualbox is great, I thought I'd add a basic docker setup if someone would be interested in running AIS inside a Docker container instead. 
Placed it on the GitHub wiki first, but then saw that we had all the other docs in the repo, so I'm suggesting to add it there as well?
> Running AIS inside Docker for development

- ais/common/settings.py
Static_dirs are used for additional static files
> Added static root

- templates/exhibitors/exhibitors.html
Career fair managers requested this function, now they have it
> Added search filtering and sorting in exhibitors table

- companies/migrations/0002_auto_20160920_2202.py
Well, hopefully this will fix the migration errors on the server.
> fix migration errors

- exhibitors/migrations/0004_auto_20161006_2020.py
- exhibitors/models.py
This should fix the migration error in production.
(Removed primary_key=True on the OneToOneField)
> undo remove primary key

- ais/common/settings.py
- ais/common/urls.py
- exhibitors/views.py
- orders/models.py
- orders/urls.py
- orders/views.py
- templates/base.html
- templates/events/event_list.html
- templates/orders/products.html
Added a product page that shows all products, quantities, prices and revenues. Will add CRUD functionality later.
> Product page

- events/templatetags/event_extras.py
- templates/events/event_attend.html
- templates/events/event_list.html
Before "Pending..." was shown for a declined user.
> Eventlist and attendence form shows if a user is declined

- .travis.yml
- companies/factories.py
- events/factories.py
- fair/factories.py
- fair/models.py
- people/factories.py
- test-requirements.txt
* Adds a test requirement
* Adds factories (so far for Fair, Company and Event)
Later the current (and future tests) would make use of the factories.
> Testing utils

- ais_static/style.css
Made the animationa a tad bit more exciting
> Ship bobbing

- docs/getting_started_linux.md
- docs/getting_started_mac.md
- docs/getting_started_windows.md
- requirements_local.txt
Added a local requirements without all the unnecessary stuff.
> Requirements local

- root/urls.py
- root/views.py
- templates/banquet/banquet_attendants.html
- templates/root/home.html
Added a table displaying all banquet attendants as requested by the banquet manager
> Banquet attendants

- ais/production/settings.py
- requirements.txt
* Automatic logging using Sentry.io
> Add logging setup

- lib/util.py
Function assumed that date was localtime, this is incorrect, time was UTC
> Fixed unix time

- people/views.py
This PR fixes the issue with non authorized persons looking at other persons profiles that where present in /people.
Now, you can only view your own profile, and other peoples profiles if you got the right permisson.
> People permissions

- events/admin.py
- events/models.py
An admin can now easily mark multiple eventattendences.
> Action accept decline attendence

- api/urls.py
- api/views.py
- Shows latest git commit on the server
- Time
- Python version
- Hostname
> Add status page to API

- api/views.py
Goes to the correct location now.
> Fix git location

- events/admin.py
The export to csv is only for events, not for attendences
> removed export csv from eventattendence admin

- api/serializers.py
- api/urls.py
- api/views.py
- recruitment/middleware.py
This is entirely untested on real data
> Added banquet placements to API, with mocked data

- api/serializers.py
- exhibitors/admin.py
and added job title to banquet api ;)
> Fixed banqet admin bug

- events/admin.py
* Adds the Acceptance and Rejection forms to the Event admin
* Formatting of file
> Add rejection and acceptance mail to event admin

- ais/common/settings.py
- ais/production/settings.py
- ais_nginx.conf
- api/views.py
- local_settings.py
> Gzip Etags Caching

- api/serializers.py
> Add startup to serializer

- api/serializers.py
Unfortunately there's not much time to implement maps etc. in ais (todo next year), so this will have to suffice.
> Add location to serializer

- register/forms.py
- templates/sales/sales_list.html
Removed Campain
Removed confirmed box in create user
> Sales update

- register/urls.py
- templates/register/index-post-register-deadline.html
- templates/register/login.html
Close initial registration for companies, see register/urls.py to open registration again
> closed initial registration

- register/urls.py
- templates/register/index-post-register-deadline.html
- templates/register/login.html
Tested on ais2 and works fine. Companies are not able to reach register/signin or register/new_company
> closed initial registration for companies

- local_settings.py
- recruitment/middleware.py
- register/urls.py
- root/urls.py
- templates/register/reset_password_confirm.html
- templates/register/reset_password_email.html
third time is a charm, moved everything back to register app
> reset password

- register/admin.py
Added functionality for exporting signupLog to csv format from admin view
> Sales csv export

- register/views.py
- templates/register/complete_confirm_email.html
The text in the template for the email (templates/register/complete_confirm_email.html) needs to be added!
> Registrate exhibitors email confirm

- ais_static/login-home.css
- static/login-home.css
- templates/register/home.html
- templates/register/login.html
Updated login and welcome template for the complete registration. 
Test: Compared with the design in the drive-folder (IT/UX-CR/Final Application/Designs)
> Login welcome template

- register/forms.py
- templates/register/login.html
Updated the design for login-template
> Login template design

- ais_static/login-home.css
- register/forms.py
- register/urls.py
- register/views.py
- templates/register/change_password.html
- templates/register/reset_password.html
- templates/register/reset_password_confirm.html
- templates/register/reset_password_done.html
Updated the design for the reset password and change password views.
Test: The design should be similar to the login view so I compared my changes with it.
> Reset password design

- ais_static/complete_registration.css
- ais_static/js/complete_registration.js
- static/complete_registration.css
- static/js/complete_registration.js
- templates/register/exhibitor_form.html
Updated visuals for banquet, nova, sture. Added logout button. Code for submission modal, but not used yet.
> Updated visuals

- ais_static/complete_registration.css
- ais_static/js/complete_registration.js
- register/forms.py
- register/urls.py
- register/views.py
- static/complete_registration.css
- static/js/complete_registration.js
- templates/register/exhibitor_form.html
- templates/register/finished_registration.html
Some minor design stuff ( login placeholder and design for confirm & save tab). Fixed css bug where titles overlapped in nova tab.
Removed back button on start tab.
I did add a 'thank you' template and made submit button redirect to this template instead of back to form again. This might be redundant since @axelinternet did a modal for this.
> More cr ui design

- companies/views.py
- templates/companies/contact_form.html
A contact created in the sales view didn't get an email when entering email in the reset_password view. The solution was to also create a user when creating a contact (in the sales view) and connect to the contact. 
Test: Created a new contact in the sales view and tried to signin and reset password for that contact. It worked.
> Modified contact_create to also create a user

- ais_static/complete_registration.css
- ais_static/js/complete_registration.js
- register/forms.py
- static/complete_registration.css
- static/js/complete_registration.js
- templates/register/exhibitor_form.html
- templates/register/finished_registration.html
#hardcodingalltheway
When entering the Confirm tab, a js function looks through a hardcoded list of ids (which is all the ids for products in the form) and checks the value for each element. All the orders are dynamically added to the form and changes live, without saving the form.
Testing: Entered the Confirm tab with existing orders loaded from form. The orders in the new ORDER CONFIRMATION section were correct. Went back to the other tabs and changed some orders and revisited the Confirm tab. The ORDER CONFIRMATION section were updated and still correct.
> Did some javascript magic and added ordered products in confirm tab.

- register/views.py
Adds base kit when the exhibitor form is submitted.
> Add base kit

- register/views.py
Let longest product name(and max amount of products) be 0 if there are no chosen products.
> Submit-bug

- register/forms.py
- register/views.py
product as select field now works for db, email, js on confirm and submit and preloads form fields, that is the bug where exhibitors requesting extra stand area and height should work completely.
Things to test:
1. If products are selected and saved the summary on confirm & submit should be updated
2. The product on the db should be updated/created
3. The email should contain the correct info
4. On logging out and in the correct products should be preloded into the selection fields
This is live on ais2 and works there.
> Bugfix product multifield

- scripts/orders-bugfix.py
Script to fix faulty orders in db. Worked on ais2.
> Fix db script

- people/models.py
test if this is the issue for kth single-signon when creating new users
> removing the override safe functionality for pictures in Profile models

- exhibitors/views.py
testing a new method for sending mass mail
> Confirmation mail

- exhibitors/urls.py
- exhibitors/views.py
- templates/exhibitors/cr_receipt.html
- templates/exhibitors/emails_confirmation.html
- templates/exhibitors/exhibitor.html
- templates/exhibitors/exhibitors.html
- templates/exhibitors/send_emails.html
A button at each exhibitor to send an email with their ordered products. 
Test:
- Sends an email to the correct exhibitor.
- The text is correct for that exhibitor -> Right orders, right total price and right name for the Company
- Everything looks ok.  Text is correct for sending one mail instead of for all exhibitors.
> Function for sending email to one exhibitor separatley

- templates/exhibitors/cr_receipt.html
- templates/exhibitors/emails_confirmation.html
- templates/exhibitors/exhibitors.html
When looking at the actual mail, some things looked weird. This changes that.
> Changed some things in the email that looked weird

- recruitment/tests.py
- recruitment/views.py
- register/forms.py
> Revert "Interview bug"

- exhibitors/views.py
- templates/exhibitors/send_emails.html
> Revert "Email contact bug"

- events/admin.py
- exhibitors/admin.py
- orders/admin.py
- register/admin.py
> Revert "Csv exhibitor + admin views"

- events/admin.py
- exhibitors/admin.py
- exhibitors/views.py
- orders/admin.py
- recruitment/tests.py
- recruitment/views.py
- register/admin.py
- register/forms.py
- templates/exhibitors/send_emails.html
> Csv exhibitor

- templates/root/home.html
Made sure that there was a link to fairs/{year}/banquet in templates/root/home.html
> Correct link to Banquet in templates/root/home.html

- api/views.py
Make sure organization looks like before (gives an error in ais2) and makes sure that nothing done in this branch has affected this error.
> Changed organization to look like before

- banquet/urls.py
- banquet/views.py
- register/forms.py
- register/urls.py
- register/views.py
- templates/banquet/banquet_attendant.html
- templates/register/create_external_user.html
Test: look at fairs/2017/banquet. Click on 'new'. Create new attendant. Click on new attendants name and edit it. Go to fairs/2017/banquet/signup and signup!
> Fixed noreversematch error 

- banquet/forms.py
- banquet/views.py
- recruitment/middleware.py
- register/urls.py
- register/views.py
- templates/register/create_external_user.html
Basic create/edit banquet attendats from fairs/year/banquet
> Banquet app

- templates/events/event_attendants.html
> Added column for attendand email

- register/views.py
ExternalUserForm should be imported in register/views.py.
Go to fairs/2017/banquet/signup
> missed import in register/views.py

- api/serializers.py
- api/views.py
Test:
Api/exhibitor should not return error if there are a location for one exhibitor, if there are not a location for another exhibitor and if there are not a contact for one exhibitor.
> Make it work even if some fields does not exists

- banquet/models.py
when creating a banquet attendant in fairs/2017/banquet/attendant/new or when creating one in external signup in fairs/2017/banquet/signup. You can't choose the ticket type in banquet/signup but it should default to student ticket
> default ticket type is stuent

- api/serializers.py
- api/views.py
- exhibitors/models.py
- register/views.py
- student_profiles/migrations/0001_initial.py
Works in ais2! See #392 for reference
> Exhibitor transport update

- api/tests.py
- api/urls.py
- api/views.py
- recruitment/middleware.py
Implemented PUT protocol for /api/student_profile?...
Also switched the whole /api/ tree to not require a login.
Make sure you can't access other parts of website without a login and the tests run fine.
And yes, this is a fresh PR, I think the last one glitched out with github not supplying all changes to TRAVIS.
> Api student profile put

- banquet/admin.py
- banquet/forms.py
To test: 
- go to /admin/banquet/banquetteattendant/ and check some attendants and then export as csv. It should work
> Fixed error in banquet csv export

- register/urls.py
- templates/register/create_external_user.html
added a kth login btn in register/external/signup. Login and register works on ais2 already. Just need to test kth button on ais2
> kth login btn

- register/views.py
when you are logged in with your account OR kth account in register/external/signup you should be redirected to fairs/{year}/banquet/signup !
> correct redirect when logged in

- api/serializers.py
- api/views.py
Only added that the exhibitor's id is shown in the api via the serializers.py file. To test it just go to api/exhibitors and make sure you can see the id's
> added id to exhibitor api

- exhibitors/views.py
Go to fairs/{year}/exhibitors/{id}/banquette_attendant/new and create a banquet attendant for the exhibitor. The test is to see that the banquette attendant that is created has the relevant fair in it's field value.
> banquet attendant in exhibitor view has relevant year

- matching/migrations/0031_auto_20171029_2208.py
- matching/migrations/0031_auto_20171030_1602.py
- matching/migrations/0032_adding_regions_20171029_2222.py
Had some problems with migrations dependencies in ais2. This should fix that.
> Fixed migrations dependencies

- api/deserializers.py
- api/tests.py
- api/views.py
Test to manually do a PUT request to ais2 for "regions" and "continents". (Format: '{"regions": [1,2,3..], "continent": [1,2,3..]}'. 
Run tests.
> Api for continents and regions

- student_profiles/migrations/0008_auto_20171104_1526.py
Removed explicit default, as it seems to be baked in on the server, but not local client
> Tweaked the migration

- banquet/tests.py
- banquet/urls.py
- banquet/views.py
- recruitment/middleware.py
- templates/banquet/table_placement.html
Test: go to fairs/2017/banquet/placement
If not logged in/ does not have a attendant you will be redirected to fairs/2017/banquet/signup
> basic view for viewing placement

- matching/algorithms/main_classify.py
- matching/views.py
- templates/matching/overwatch.html
> Matching algorithm mk1

- templates/banquet/external_signup.html
To test: 
- Go to /fairs/2017/banquet/signup 
- You should see "Sign up is closed!" instead of the sign up form
Works in ais2!
> Tempfix to close banquet signup. Commented away the signup form

- register/forms.py
- register/views.py
1. all logged in users should be redirected from external signup to placement
2. password in external should be a "password field" - the password should not be seen basically
> correct redirect and password field not shown

- register/forms.py
> Exterbal banquet users

- ais_nginx.conf
…s. Some browsers and frameworks provide the Accept-Encoding header that is rejected by the ais
> Fix api bug

- api/views.py
> Api recruitment

- exhibitors/management/commands/generate_bills.py
Minor output change to hogia file.
> Adjusted some parameters in the hogia import file

- accounts/README.md
- ais/README.md
- api/README.md
- banquet/README.md
- companies/README.md
- events/README.md
- exhibitors/README.md
- exhibitors/management/commands/generate_bills.py
- fair/README.md
- lib/README.md
- locations/README.md
- matching/README.md
- news/README.md
- orders/README.md
- people/README.md
- recruitment/README.md
- register/README.md
- requirements.txt
- root/README.md
- sales/README.md
- scripts/README.md
- student_profiles/README.md
Added a README file to all apps in the ais project.
These files summarize what the app is and how it is used.
> App documentation

- recruitment/tests.py
- recruitment/urls.py
Made all views in recuitment viewable
> Removed tempfix in recruitment urls

- recruitment/views.py
Now armada members who have permission to view recruitment applications, can see applications only below themselves in the hierarki
> fixed recruitment application access

- accounts/README.md
- ais/README.md
- api/README.md
- banquet/README.md
- companies/README.md
- events/README.md
- exhibitors/README.md
- fair/README.md
- lib/README.md
- locations/README.md
- matching/README.md
- news/README.md
- orders/README.md
- people/README.md
- recruitment/README.md
- register/README.md
- root/README.md
- sales/README.md
- scripts/README.md
- student_profiles/README.md
Added a README file to all apps in the ais project.
These files summarize what the app is and how it is used.
Note: Travis builds fail, however this PR adds no functionality to speak of to warrant that failure.
> App documentation.

- .travis.yml
Created another PR with this fix since the last one became so messy! 🥇
> Travis fix again

- events/api.py
- events/api_urls.py
- events/serializers.py
- events/static/js/signup/actions.js
- events/static/js/signup/api.js
- events/static/js/signup/components/Manage.js
- events/static/js/signup/components/Teams/TeamInformation.js
- events/static/js/signup/components/Teams/index.js
- events/static/js/signup/index.js
- events/static/js/signup/reducer.js
- package.json
Leaders of teams can now edit the team name and remove members
> Admin team edit

- events/api.py
- events/models.py
- events/serializers.py
- events/static/js/signup/components/Header.js
- events/static/js/signup/components/Manage.js
- events/static/js/signup/components/SignupForm.js
- events/views.py
- templates/events/event_edit.html
- templates/events/participant_list.html
Fix a couple of bugs related to events
> Minor changes

- recruitment/models.py
- requirements.txt
Turned out to be really easy to implement. No major changes to functionality and the change has been tested. 
An interviewer must be assigned first before it will check for recommended role and rating, but a time slot is not mandatory to assign. 
Let me know if any changes are necessary.
If you integrated the other stories first, I can rebase this on top easily.
> 002 done status

- accounting/views.py
This merge is only to test the email functionality in production. The code will be restored and the real functionality will later be added.
> testing email functionality

- exhibitors/forms.py
- exhibitors/views.py
- register/views.py
- templates/exhibitors/create.html
With this feature the sales team can add an exhibitor even if the initial contract has not been signed as is the normal case. This added feature is in the exhibitors app.
> 067 Add option to add exhibitor even if IR has not been completed

- templates/base.html
The new it-support channel is reached via the OT slack. Then, team leaders and coordinators can also ask questions and write feedback.
> Updated support slack channel

- recruitment/urls.py
- recruitment/views.py
- templates/recruitment/recruitment_application_table.html
- templates/recruitment/recruitment_period.html
in views.py tab indentation is used now instead of space indentation
> 083 recruitment selection process

- events/api.py
- events/static/js/signup/components/QRCode.js
- events/static/js/signup/components/SignupForm.js
- events/static/js/signup/components/Stripe.js
- package.json
- templates/events/event_signup.html
The event signup platform now uses Stripes SCA-ready APIs, namely Payment Intents. This PR also contains an additional React package from stripe.
> Updated payment using Stripe in events

- exhibitors/api.py
This is a continuation of #645, to fix a small typographical error.
> Corrected a typographical error

- ais_static/style.css
- events/api.py
- events/api_urls.py
- lib/CAS_callback.py
- lib/KTH_Catalog.py
- templates/events/event_edit.html
- templates/events/participant_list.html
The same description for #658 applies here.
Additionally, this PR includes:
- A **button** for updating participants in the event view.
- Change of KTH API endpoint to **https://api.kottnet.net/kth/** for retrieving user details.
Apart from the 'Steps to reproduce' included in #658, this PR also requires:
1. Deleting user details in http://localhost:8080/admin/auth/user/
2. Add this user as participant to the event.
3. Click on 'Update participants'
The user details shown in the participants table should be updated successfully. In case it is not updated, verify that the user details can be retrieved from 'https://api.kottnet.net/kth/<kth_id>'
> Add update participants button

- recruitment/views.py
The code will look for a Head of Human Resource first and if the person is not found then it will look for a Project Manager and the last fallback will be Armadas Support person.
> 670: Change hard coded contact info in confirmation mail to applicants

- kth_login/views.py
Read more from the [issue](https://github.com/armada-ths/ais/issues/690)
> 690: Hotfix: User are having problem KTH login redirect

- ais/common/urls.py
- fair/views.py
- register/urls.py
- templates/register/outside/reset_password_complete.html
- urls/urls.py
From the sentry.io we have generated some url path which causes errors.
**Fair**
**As company**
> #709: Hotfix: URL issues

- dev-runserver.sh
- events/static/js/signup/components/SignupForm.js
- events/views.py
- scripts/vagrant/provision.sh
> #711: Hotfix: Bug with uploading images for event

- recruitment/views.py
Fixed recruitment redirection with annotation
> #722: Hotfix: Recruitment redirection 

- ais/common/settings.py
- ais/production/settings.py
- ais_static/django-dynamic-formset/demo/settings.py
- requirements.txt
- static/django-dynamic-formset/demo/settings.py
This PR makes it possible to turn off the debuggers without loosing the styling (CSS) of the website.
> Fixes For CSS when debugger is FALSE

- banquet/urls.py
- banquet/views.py
- templates/banquet/manage_participants.html
Added CSV export for participants in banquet
> Button for export of Banquet participants

- templates/register/inside/registration_complete.html
Add text in complete registration (AIS): Add information on the complete registration page that the TOTAL TO PAY is excluding VAT
> Add text in complete registration (AIS)

- ais/common/settings.py
- ais/production/settings.py
- requirements.txt
Fixes #767 by changing debug flag in the production settings file.
---
- https://app.asana.com/0/0/1204038385197069
- https://app.asana.com/0/0/1204053576959592
> fix: Disable debug in production

- .github/PULL_REQUEST_TEMPLATE.md
> doc: Add pull request template

- .github/CODE_OF_CONDUCT.md
> doc: Add code of conduct

- register/models.py
Fixes: #783 by adding a check if `company_contact` exists before trying to access it. If it does not exist, use a '-' value.
Was not able to reproduce locally, but the error description on the live page was sufficient to figure out the error.
---
- https://app.asana.com/0/0/1204139092020127
> Add check for no company contact for signup log

- register/views.py
Fixes: #790 by changing roles on one of the filters in the contact card to match the new role.
---
- https://app.asana.com/0/0/1204143128722509
> fix: Add 'Head of Business Relations' as a contact card

- templates/register/inside/registration_initial.html
Fixes: #792 by updating the link to the new file
🚨⚠️ Do NOT merge this until https://github.com/armada-ths/armada.nu/pull/748 is merged and published
---
- https://app.asana.com/0/0/1204237759954773
> fix: Catalog year in 'more info'

- templates/login.html
HOTFIX: https://register.armada.nu has been sent out to companies but there is no way to get to the actual company signup page which is https://register.armada.nu/register/
> hotfix: Link to company registration from default registration

- .vscode/settings.json
Fixes: #801 by adding formatting options to the vscode settings file.
> feat: Add VSCode auto format on save

- Dockerfile
- docker-compose.yml
Fixes: #798 by changing the docker port from 8080 to 3000.
> fix: Change docker web port from 8080 to 3000

- .dockerignore
- Dockerfile
Fixes: #787 by adding two build steps, frontend and backend, and restructuring the order of commands.
> feat: Parallelize docker build

- .github/workflows/format.yml
Fixes: #807 by removing the verbose flag for the black program runner.
> fix: Remove verbose output of format program

- api/views.py
- recruitment/models.py
Fixes: #817 by appending all optional questions to the `/recruitment_data` endpoint.
```json
[{
"<p>Custom field question?</p>": "Radio 2", <-- this is an optional question
"status": null,
"profile_gender": "male",
"programme": "KTH PROGRAM 1",
"profile_preferred_language": "English"
}]
```
> fix: Add optional questions to recruitment data

- api/util.py
Fixes: #819 by collecting all unique header values and outputting the values of the items in the right order.
> fix: Output CSV values in the right order

- api/views.py
Fixes: #824 by adding additional fields.
> feat: Add additional recruitment fields to recruitment statistics endpoint

- register/forms.py
- register/views.py
- templates/register/inside/registration_initial.html
> fix: Update year of registration header

- docs/README.md
Fixes: 
#839 by adding documentation for creating a super user for accessing a locally hosted AIS instance
#840 by adding documentation for creating a new fair in a locally hosted AIS instance.
> doc: Onboarding documentation

- docker-compose.yml
- docs/README.md
- init-dev-environment.sh
Fixes: #846 by fixing the setup of copying a production database, and creating a script `init-dev-environment.sh` which migrates the local database as well as creates a super user.
> feat: Add migrations and createsuperuser tool

- docs/README.md
- make-migration.sh
Fixes: #810 by adding documentation regarding database migrations.
> doc: Add database migrations docs

- docs/README.md
> doc: Fix ambiguous super user docs

- .github/workflows/pr-style.yml
> Remove PR name requirement pipeline

- ais/production/settings.py
Fixes: #866 by removing sentry environment variables, making the production file similar to the local file which we know works in production.
> fix: Remove sentry logging

- ais_static/registration_style.css
- templates/register/outside/create_user.html
The styles for the redirect link to the 'Create a new company' form in https://register.armada.nu/register/user has been slightly changed for it to be more noticeable to users.
The link is now part of the 'paragraph' tag, not the other way around, making the link easier to notice than before. Moreover, the link is now underlined, not only to make it follow a standardized URL style but also to make it even easier to notice.
Fixes: #858
> feat: 'Create Company' Redirect Link Style Minor Update

- companies/views.py
- templates/companies/companies_view.html
Fixes: #870 by making profile not throw 404 if it doesn't exist.
> fix: Fix companies crashing locally

- api/urls.py
- api/views.py
Fixes: #875 by replacing the old `/api/status` endpoint (which always gave an error) with a `/api/dates` endpoint.
> feat: Add fair dates API

- ais/production/settings.py
> fix: Allow cors for armada.nu

- ais/production/settings.py
> fix: Allow localhost cors

- docs/CONTRIBUTING.md
> doc: Update contribution

- register/api/registration/cr.py
- register/api/registration/types/registration.py
- register/api/registration/types/util.py
> feat: Add before CR state

- ais/common/settings.py
- ais/common/urls.py
- api/urls.py
- api/views.py
- companies/views.py
- requirements.txt
- templates/companies/companies_view.html
- templates/magic_link/error.html
- templates/magic_link/logmein.html
Fixes: #882 
---
- https://app.asana.com/0/0/1204650493731358
> feat: Add magic login link

- ais/local/settings.py
> chore: Remove boto3 storage variable for local settings

- .vscode/settings.json
> chore: Remove auto format on save for VS Code

- init-dev-environment.sh
> doc: Add echo statements to init-dev-environment script

- static/js/stepform.js
> fix: Remove local url from step form

- register/api/__init__.py
- register/api/registration/__init__.py
> feat: Remove todos

- apps/complete_registration/src/forms/primary/product.page.tsx
- apps/complete_registration/src/screens/form/sidebar/FormSidebarCartSummary.tsx
- apps/complete_registration/src/store/products/products_slice.ts
> fix: Fix #947, descriptions for categories

- register/views.py
> fix: Remove contract type

- register/views.py
> Revert "fix: Remove contract type"

- apps/complete_registration/src/forms/form_access.ts
- apps/complete_registration/src/main.tsx
- apps/complete_registration/src/screens/dashboard/FormCard.tsx
- apps/complete_registration/src/screens/dashboard/screen.tsx
- apps/complete_registration/src/screens/form/screen.tsx
- apps/complete_registration/src/shared/InfoScreen.tsx
- apps/complete_registration/src/shared/useLoadData.tsx
- apps/complete_registration/src/store/form/form_selectors.ts
- apps/complete_registration/src/store/products/products_slice.ts
> fix: Make form routes reloadable, add form/:formId

- companies/views.py
- register/api/registration/cr.py
- register/api/registration/types/cr.py
- templates/companies/email.html
> feat: Add showing missing contact information

- companies/views.py
- templates/companies/email.html
> feat: Add showing missing contacts everywhere in email view

- register/api/registration/types/base64image.py
> fix: Uploading image with url instead of base64 raising validation error

- apps/complete_registration/src/forms/primary/package_select.page.tsx
- apps/complete_registration/src/store/products/products_selectors.ts
- apps/complete_registration/src/store/products/products_slice.ts
> fix: Allow hidden packages when confirming signup

- apps/complete_registration/src/store/products/products_slice.ts
> fix: Remove bypass check

- Dockerfile
- apps/complete_registration/.dockerignore
> fix: Fix output.css file in build step

- apps/complete_registration/src/forms/transport/transport_info.page.tsx
> fix: Fix armada text page

- docs/README.md
> feat: Add solution to CRLF problem in entrypoint.sh

- .vscode/settings.json
> python specific format on save

- companies/views.py
- templates/companies/companies_list.html
> show total companies, fix page rounding bug

- templates/recruitment/recruitment_application_new.html
> fix role description styling in recruitment application

- ais/production/settings.py
> feat: Add stripe test keys

- ais/production/settings.py
> feat: Add real stripe keys

- events/views.py
- templates/events/event_not_published.html
> fix: Show event not published

- fair/admin.py
> fix change/add lunchticket crashing

- templates/exhibitors/exhibitor_coordinates.html
> add help text for adding map coordinates

- fair/admin.py
- improved_admin.py
> fixed autocomplete for fairday

- exhibitors/forms.py
- exhibitors/models.py
- exhibitors/urls.py
- exhibitors/views.py
- templates/exhibitors/exhibitor.html
- templates/exhibitors/exhibitor_check_in.html
- templates/exhibitors/exhibitor_contact_persons.html
- templates/exhibitors/exhibitor_coordinates.html
- templates/exhibitors/exhibitor_details.html
- templates/exhibitors/exhibitor_fair_location.html
> add fair location tab and form to exhibitor views

- docs/README.md
- util/__init__.py
> doc: Update documentation

- register/api/registration/__init__.py
> fix: Oups something went wrong after CR

- banquet/views.py
- templates/banquet/invitation_external.html
- templates/banquet/invitation_internal.html
> feat: Add ticket link in banquet invite form

- banquet/forms.py
- banquet/functions.py
- banquet/urls.py
- banquet/views.py
- templates/banquet/manage_imported_invitations.html
- templates/banquet/manage_invitations.html
Fixes: #1076 by adding a textarea which can be used for importing excel data.
Also does some validation of the data. Emails are required, empty names give warning, no price gives error. Already added participants are shown, and are not added again.
> feat: Add importing banquett invitations from excel

- banquet/forms.py
> fix: Fix banquet import price setting to 0

- templates/banquet/manage_imported_invitations.html
> fix: Add duplicate message on email instead of name

- banquet/forms.py
- banquet/functions.py
- banquet/views.py
- templates/banquet/manage_imported_invitations.html
- templates/banquet/manage_invitation.html
> feat: Add send email checkbox to banquett

- ais/production/settings.py
> feat: Allow netlify cors origin

- events/api.py
- events/forms.py
- events/static/js/signup/components/Question.js
> feat: Add event file size limit

- fair/api.py
Child products are not necessary since when they are created they will be treated as regular products, previously we got duplicates
Fixes: #
> fix: Remove child_product count

- apps/complete_registration/src/forms/lunch_tickets/lunch_tickets.tsx
> lint: Test linting

- apps/complete_registration/src/forms/lunch_tickets/lunch_ticket_create.page.tsx
> fix: Add information box for creating lunch tickets

- recruitment/admin.py
Fixes: #1068 
Essentially the same kind of bug found in #1050
> fix adminsite recruitmentapplication search crashing

- banquet/api.py
> fix: Add searching banquett tickets for non-ais users, name and email

- banquet/api.py
- banquet/static/js/scan_tickets/TicketList/index.js
> feat: Add showing checked in participants in banquet scan ticket list

- templates/exhibitors/exhibitors.html
> fix: Fix exhibitors crashing

- banquet/urls.py
- banquet/views.py
- templates/banquet/dashboard.html
- templates/banquet/manage.html
> fix: Fix banquett ticket scanning for multiple banquetts

- banquet/api.py
- banquet/api_urls.py
- banquet/static/js/scan_tickets/api.js
> fix: Fix scan ticket list in scan tickets for multiple banquets

- banquet/views.py
> fix: Remove after party ticket link

- docs/README.md
> doc: Add dashboard instructions

- fair/admin.py
- fair/models.py
- improved_admin.py
- recruitment/admin.py
- recruitment/admin_filters.py
> fix: Admin dashboard sorting and filtering

- init-dev-environment.sh
> feat: Add custom argument to init dev environment

- exhibitors/api.py
> chore: Remove exhibitor contact in api

- recruitment/views.py
> fix: HR person for recruitment email

- recruitment/views.py
> fix: HR profile

- accounting/views.py
> fix: Company summary now includes total

- ais_static/style.css
> fix: Navbar overflow

- .github/PULL_REQUEST_TEMPLATE.md
> doc: Remove PR template checkboxes

- api/urls.py
- api/views.py
- companies/api.py
- companies/api_urls.py
- dashboard/api/registration/types/registration.py
- dashboard/api/registration/types/serializer.py
- fair/models.py
> feat: Add interested in API

- ais/production/settings.py
> Remove sending system emails

- ais/production/settings.py
> fix: Add longer aws signature durations

- ais/production/settings.py
> fix: Remove AWS s3 url signatures

- .env.example
- .gitignore
- Makefile
- apps/dashboard/pnpm-lock.yaml
> feat: Add setup script for AIS

- apps/dashboard/package.json
> fix: Change appending output css to asset styles instead of replacing

- templates/companies/companies_list.html
> feat: Add CRM datatable

- Dockerfile
> Fix: pnpm node version in docker file

- Dockerfile
> fix: Docker dashboard workdir

- templates/companies/companies_list.html
> fix: Remove datatable search in CRM

- apps/dashboard/src/screens/dashboard/ContactBubble.tsx
- util/__init__.py
> Company responsible connected to dashboard contact bubble

- docs/README.md
> doc: Update onboarding

- templates/recruitment/recruitment_application_interview.html
> fix: Recruitment image

- util/__init__.py
> fix: Fix getting current fair and user for dashboard

- util/__init__.py
This reverts commit 11f94620b213fdce523f3bb835e8cf0431bc1454.
Fixes: #
> Revert: "fix: Fix getting current fair and user for dashboard (#1215)"

- util/__init__.py
> fix: Add checking for react port 5173

- templates/companies/groups.html
> docs: Add info boxes to group page to inform users of how it works

- companies/views.py
- templates/companies/statistics.html
Added a line with all signatures in the graph in fairs/2024/companies/statistics:
> Lucia/feature/add 'all' line in ais statistics

- apps/dashboard/src/main.tsx
- apps/dashboard/src/screens/dashboard/timeline_steps.tsx
- apps/dashboard/src/store/company/company_slice.ts
- dashboard/api/registration/types/registration.py
- dashboard/api/registration/types/util.py
- docs/README.md
> fix: Remove rejected status for companies without IR

- Dockerfile
> fix: pnpm version in docker file

- apps/dashboard/src/forms/core_values/diversity_index.page.tsx
> fix: Diversity page

- apps/dashboard/src/forms/ir_signup/ir_registration.page.tsx
> fix: Navigation after IR early return

- apps/dashboard/src/forms/fr_accounting/components/ProductOrderingCard.tsx
- apps/dashboard/src/forms/fr_accounting/package_select.page.tsx
> fix: Max quantity badge

- apps/dashboard/src/forms/core_values/diversity_index.page.tsx
> fix: Diversity index url

- dashboard/api/registration/response.py
> fix: Remove print

- apps/dashboard/src/forms/ir_signup/ir_registration.page.tsx
- apps/dashboard/src/screens/dashboard/timeline_steps.tsx
> fix: Texts

- apps/dashboard/src/forms/fr_accounting/summary.page.tsx
> fix: Total price

- apps/dashboard/src/screens/form/screen.tsx
> fix: Stickyness of forms

- dashboard/api/registration/response.py
> fix: Add only sending IR email when contract is timely

- apps/dashboard/src/forms/receipt/order_details.page.tsx
> fix: Fix order detail card api call

- exhibitors/api.py
> fix: Fix exhibitors call

- exhibitors/api.py
> fix: Exhibitor status api

- templates/banquet/invitation_internal.html
For some reason this template file has been reformatted into a broken state.
> fix: Broken banquet template

- people/urls.py
- people/views.py
> fix: Contacts page performance

- Dockerfile
- ais/common/settings.py
- requirements.txt
This reverts commit 56f110db0760ce9f8c0604dbd56219e0b0b04c48.
Postgres != postgis, this crashes some pages
> Fix: Revert "fix: Add DB connection pool library (#1259)"

- ais/common/settings.py
This reverts commit d742c4d33d108b56368012de07df324de19f9fff.
Fixes: #
> Revert "fix: Add CONN_MAX_AGE to database settings (#1268)"

- ais/common/settings.py
> fix: Disable persistant connections

- events/static/js/signup/components/SignupForm.js
> fix: Event signup variable

- banquet/functions.py
- banquet/views.py
- templates/banquet/email/invitation.html
- templates/banquet/manage_participant.html
- templates/banquet/participant_display.html
- util/email.py
> fix: Add banquet fixes

- templates/banquet/email/invitation.html
> fix: Format of banquet email date

- banquet/urls.py
- banquet/views.py
- templates/banquet/manage_handle_email.html
> feat: Add feature to resend emails

- banquet/functions.py
- banquet/views.py
- templates/banquet/email/reminder.html
- templates/banquet/manage_handle_email.html
> feat: Add banquet email reminders

- banquet/functions.py
- banquet/views.py
- templates/banquet/manage_handle_email.html
> fix: banquet reminder emails

- banquet/views.py
- templates/banquet/manage_handle_email.html
> fix: Email reminders for banquet

- banquet/forms.py
- banquet/views.py
- templates/banquet/manage_participant.html
> fix: Banquet participant dietary list

- register/api.py
> fix: Add lower email address to registration

- apps/dashboard/src/screens/dashboard/ContactBubble.tsx
- util/__init__.py
> feat: Add host as contact person

- banquet/views.py
- templates/banquet/dashboard.html
- templates/banquet/email/after_party_invite.html
> feat: Add banquet after party
